/*
 * Aurora Kernel - Registry Hive Operations (stubs)
 */

#include "hive.h"

NTSTATUS HiveCreateKey(IN PHIVE Hive, IN PCSTR KeyPath, OUT PUINT32 KeyCell)
{
    UNREFERENCED_PARAMETER(Hive);
    if (!KeyPath || !KeyCell) return STATUS_INVALID_PARAMETER;
    /* Stub: pretend key created/found */
    *KeyCell = 1;
    return STATUS_SUCCESS;
}

NTSTATUS HiveFindKey(IN PHIVE Hive, IN PCSTR KeyPath, OUT PUINT32 KeyCell)
{
    UNREFERENCED_PARAMETER(Hive);
    if (!KeyPath || !KeyCell) return STATUS_INVALID_PARAMETER;
    return STATUS_NOT_FOUND;
}

NTSTATUS HiveDeleteKey(IN PHIVE Hive, IN PCSTR KeyPath)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(KeyPath);
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS HiveEnumerateKeys(IN PHIVE Hive, IN UINT32 ParentKey, IN UINT32 Index, OUT PCHAR KeyName, IN OUT PUINT32 NameSize)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(ParentKey);
    UNREFERENCED_PARAMETER(Index);
    UNREFERENCED_PARAMETER(KeyName);
    UNREFERENCED_PARAMETER(NameSize);
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS HiveSetValue(IN PHIVE Hive, IN UINT32 KeyCell, IN PCSTR ValueName, IN UINT32 Type, IN PVOID Data, IN UINT32 DataSize)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(KeyCell);
    UNREFERENCED_PARAMETER(ValueName);
    UNREFERENCED_PARAMETER(Type);
    UNREFERENCED_PARAMETER(Data);
    UNREFERENCED_PARAMETER(DataSize);
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS HiveGetValue(IN PHIVE Hive, IN UINT32 KeyCell, IN PCSTR ValueName, OUT PUINT32 Type, OUT PVOID Data, IN OUT PUINT32 DataSize)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(KeyCell);
    UNREFERENCED_PARAMETER(ValueName);
    UNREFERENCED_PARAMETER(Type);
    UNREFERENCED_PARAMETER(Data);
    UNREFERENCED_PARAMETER(DataSize);
    return STATUS_NOT_FOUND;
}

NTSTATUS HiveDeleteValue(IN PHIVE Hive, IN UINT32 KeyCell, IN PCSTR ValueName)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(KeyCell);
    UNREFERENCED_PARAMETER(ValueName);
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS HiveEnumerateValues(IN PHIVE Hive, IN UINT32 KeyCell, IN UINT32 Index, OUT PCHAR ValueName, IN OUT PUINT32 NameSize)
{
    UNREFERENCED_PARAMETER(Hive);
    UNREFERENCED_PARAMETER(KeyCell);
    UNREFERENCED_PARAMETER(Index);
    UNREFERENCED_PARAMETER(ValueName);
    UNREFERENCED_PARAMETER(NameSize);
    return STATUS_NOT_IMPLEMENTED;
}

NTSTATUS HiveCompact(IN PHIVE Hive)
{
    UNREFERENCED_PARAMETER(Hive);
    return STATUS_SUCCESS;
}
